// Code generated by mockery v2.20.0. DO NOT EDIT.

package consumer

import mock "github.com/stretchr/testify/mock"

// MockConsumerHandler is an autogenerated mock type for the ConsumerHandler type
type MockConsumerHandler struct {
	mock.Mock
}

// ProcessOhlc provides a mock function with given fields: in
func (_m *MockConsumerHandler) ProcessOhlc(in []byte) {
	_m.Called(in)
}

type mockConstructorTestingTNewMockConsumerHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConsumerHandler creates a new instance of MockConsumerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConsumerHandler(t mockConstructorTestingTNewMockConsumerHandler) *MockConsumerHandler {
	mock := &MockConsumerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
