// Code generated by mockery v2.20.0. DO NOT EDIT.

package fs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDatalogic is an autogenerated mock type for the Datalogic type
type MockDatalogic struct {
	mock.Mock
}

// GetDataFromJSON provides a mock function with given fields: ctx
func (_m *MockDatalogic) GetDataFromJSON(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockDatalogic interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDatalogic creates a new instance of MockDatalogic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDatalogic(t mockConstructorTestingTNewMockDatalogic) *MockDatalogic {
	mock := &MockDatalogic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
