version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - go-tech-test

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - go-tech-test

  redis-datastore:
    image: redis:latest
    container_name: redis-datastore
    ports:
      - 6379:6379
    networks:
      - go-tech-test

  go-grpc:
    container_name: go-grpc
    build:
      context: .
      dockerfile: ./docker/go_app.Dockerfile
    ports:
      - 8080:8080
    networks:
      - go-tech-test
    restart: unless-stopped
    depends_on:
      - kafka
    volumes:
      - ./subsetdata:/subsetdata

  go-consumer:
    container_name: go-consumer
    build:
      dockerfile: ./docker/go_consumer.Dockerfile
    restart: unless-stopped
    networks:
      - go-tech-test
    depends_on:
      - kafka
  
networks:
  go-tech-test:
    driver: bridge